#!/usr/bin/env zsh

# `.functions` provides helper functions for shell.


# === Commonly used functions ===

catroll() {
    patterns=()
    while [[ "$1" == "-I" && -n "$2" ]]; do
        patterns+=("$2")
        shift 2
    done

    if [[ ${#patterns[@]} -gt 0 ]]; then
        prune=( \( )
        first=1
        for p in "${patterns[@]}"; do
            if [[ $first -eq 0 ]]; then prune+=( -o ); fi
            prune+=( -path "*/$p/*" -o -path "*/$p" -o -name "$p" )
            first=0
        done
        prune+=( \) -prune )

        find . "${prune[@]}" -o -type f -print0 \
        | while IFS= read -r -d '' file; do
            echo "### $file"
            cat "$file"
            echo
        done
    else
        find . -type f -print0 \
        | while IFS= read -r -d '' file; do
            echo "### $file"
            cat "$file"
            echo
        done
    fi
}

alias cls='printf "\033[3J\033[H\033[2J"' # "\e[3J\e[H\e[2J"

