# -- terminal -------------------------------------------------------------------
set -g default-terminal "screen-256color"

set -s focus-events on
set -g set-clipboard on

set -s extended-keys always
set -s extended-keys-format csi-u

# set -as terminal-features 'xterm*:extkeys'
set -as terminal-features ',xterm-ghostty:extkeys'

# -- general -------------------------------------------------------------------
set -q -g status-utf8 on                  # expect UTF-8 (tmux < 2.2)
setw -q -g utf8 on

set -s escape-time 10                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout

set -g history-limit 5000                 # boost history

unbind C-b
set -g prefix C-a                         # GNU-Screen compatible prefix
bind C-a send-prefix

# set -g prefix C-Space
# bind C-Space send-prefix

set -g status-keys emacs

unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"


# -- display -------------------------------------------------------------------
set -g base-index 1
set -g pane-base-index 1

set -g mouse on

set -g set-titles on          # set terminal title


# -- navigation ----------------------------------------------------------------
# create session
# bind C-c new-session

# find session
# bind C-f command-prompt -p find-session 'switch-client -t %%'

# split current window vertically
unbind %
# bind | split-window -h -c "#{pane_current_path}"
# bind \\ split-window -h -c "#{pane_current_path}"
bind _ split-window -h -c "#{pane_current_path}"
# split current window horizontally
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# window navigation
bind Tab last-window


# -- copy mode -----------------------------------------------------------------
set-window-option -g mode-keys vi

bind Enter copy-mode # enter copy mode
# bind Escape copy-mode
bind -T copy-mode-vi Escape send -X cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# -- plugins -------------------------------------------------------------------
# install tpm: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# Press prefix + I (capital i, as in Install) to fetch the plugin
# Press prefix + alt + u (lowercase u as in uninstall) to remove the plugin.
# prefix + U updates plugins

set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins/"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin "tmux-plugins/tmux-sessionist"

set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"

set -g @plugin 'timvw/tmux-assistant-resurrect'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore "on"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.tmux/plugins/tpm/tpm'
run "$XDG_DATA_HOME/tmux/plugins/tpm/tpm"

